name: Marvel API Tests

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  run-postman-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection # O nome do seu passo
        run: |
          newman run "Meus Testes com API Marvel.postman_collection.json" \
            -e "API-Marvel-Keys.postman_environment.json" \
            --env-var "publicKey=${{ secrets.MARVEL_PUBLIC_KEY }}" \
            --env-var "privateKey=${{ secrets.MARVEL_PRIVATE_KEY }}" \
            --env-var "baseUrl=${{ secrets.MARVEL_BASE_URL }}"