name: Marvel API Tests

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  run-postman-collection:
    runs-on: ubuntu-latest # O sistema operacional onde o job vai rodar

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run "Meus Testes com API Marvel.postman_collection.json" --env "API-Marvel-Keys.postman_environment.json"
        env:
          MARVEL_PUBLIC_KEY: ${{ secrets.MARVEL_PUBLIC_KEY }}
          MARVEL_PRIVATE_KEY: ${{ secrets.MARVEL_PRIVATE_KEY }}
          MARVEL_BASE_URL: ${{ secrets.MARVEL_BASE_URL }} # Opcional, se você definiu este segredo